{
 "title": "cloud_shop_monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route) (increase(http_requests_total[$__range]))",
     "legendFormat": "{{rate_interval}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "{{container}}" }
   ]
  }
 ]
}