apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: order-service   
  namespaceSelector:
    matchNames:
      - default           
  endpoints:
    - port: http          
      path: /metrics
      interval: 15s
