apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: product-service   
  namespaceSelector:
    matchNames:
      - default           
  endpoints:
    - port: http          
      path: /metrics
      interval: 15s
