apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    prometheus: prometheus-kube-prometheus-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 32090
